name: CI Pipeline

on:
  push:
    branches: ["devlop"]
  pull_request:
    branches: ["devlop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Stage
        run: |
          echo "Running Build Stage..."
          chmod +x *.sh

      - name: Run hello.sh
        run: ./hello.sh

  test:
    runs-on: ubuntu-latest
    needs: build     # Runs after build job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Stage
        run: |
          echo "Running Test Stage..."
          ./hii.sh

  deploy:
    runs-on: ubuntu-latest
    needs: test     # Runs after test job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Stage
        run: echo "Deploying Application..."
