 name: CI
 on:
   push:
    branches: [ "devlop" ]
   pull_request:
    branches: [ "devlop" ]
   workflow_dispatch:
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: chmod +x *.sh
      - name: Run a multi-line script
        run: ./hello.sh
      - name: Run hii.sh
        run: ./hii.sh
